[mfx_lib] Add JSL platform support
Intel-Media-SDK/MediaSDK pull request #2469
Opened 2020-11-10 09:24 UTC by ljia5

Add JSL platform support for mfx lib

Issue: N/A
Test: sanity tests

2020-11-10 16:51 UTC, dvrogozh requested changes
Commit message does not reflect what you actually did. You did not add JSL support to the entire msdk, you just enable fcopy support for JSL platform. Name commit accordingly. For example: `fcopy: enable support for jsl`

2020-11-12 02:55 UTC, FurongZhang submitted a review, later dismissed

2020-11-12 02:59 UTC, dvrogozh commented
@ljia5 : Changing PR title does not help. Please, fix commit message to state what you've did. Specifically: `fcopy: enable support for jsl`

2020-11-16 17:16 UTC, dvrogozh commented
@ljia5 : please, address comment...

2021-05-06 20:23 UTC, closed without merging