[HEVCe] Support B frames for all target usage with LowPower on
Intel-Media-SDK/MediaSDK pull request #2485
Opened 2020-11-16 06:03 UTC by JeremyShang

2020-11-16 06:04 UTC, JeremyShang commented
Media driver's change to support B frame for speed mode has been merged in master branch as  https://github.com/intel/media-driver/commit/63ff90528ef3fa37f5fe3e5d33ceaa8d1e54a190

2020-11-16 11:54 UTC, vilichev approved these changes

2020-11-16 16:52 UTC, uartie commented
This is the same attempt as #2440 which caused regressions.  Why are we trying to add this change again?

2020-11-16 17:10 UTC, dvrogozh requested changes
This change is **identical** to the one done before (#2440) and reverted due to reported #2475 issue. Commit message has no indication that #2475 regression was actually addressed (in any of other commits). Hence, this PR can not be merged. Please, take efforts to explain (in commit message) why we got #2475 regression and how it was fixed.

2020-11-17 00:45 UTC, JeremyShang commented
> This is the same attempt as #2440 which caused regressions. Why are we trying to add this change again?

2020-11-17 00:50 UTC, JeremyShang commented
> This is the same attempt as #2440 which caused regressions. Why are we trying to add this change again?

Hi @uartie, previously #2440 got regression due to media driver's change to support B frame for speed mode was not been merged yet into master branch at that moment. Since media driver's related change has been merged into mater branch as
intel/media-driver@63ff905, this corresponding MSDK's change can work functionally on speed mode based on the latest media driver.

2020-11-17 00:52 UTC, JeremyShang commented
> This change is **identical** to the one done before (#2440) and reverted due to reported #2475 issue. Commit message has no indication that #2475 regression was actually addressed (in any of other commits). Hence, this PR can not be merged. Please, take efforts to explain (in commit message) why we got #2475 regression and how it was fixed.

Hi @dvrogozh, sure, commit message has been updated in the latest commit. Previously #2440 got regression due to media driver's change to support B frame for speed mode was not been merged yet into master branch at that moment. Since media driver's related change has been merged into mater branch as intel/media-driver@63ff905, this corresponding MSDK's change can work functionally on speed mode based on the latest media driver.

2020-11-17 19:34 UTC, uartie commented
@JeremyShang thanks for the information.  I just tested this patch locally with latest driver and the results are good (i.e. no regression).  Cheers.

2020-11-17 20:57 UTC, dvrogozh approved these changes
Thank you for update.

2020-11-18 11:23 UTC, vilichev approved these changes

2020-11-18 12:27 UTC, dmitryermilov approved these changes

2020-11-18 12:27 UTC, merged