[doc] Added information in manual about mfxExtHEVCRefListCtrl, mfxExt…
Intel-Media-SDK/MediaSDK pull request #2553
Opened 2020-12-28 08:50 UTC by daleksan

…HEVCRefLists and mfxExtHEVCTemporalLayers

2021-01-24 17:27 UTC, dmitryermilov requested changes

2021-01-24 17:27 UTC, dmitryermilov commented on doc/mediasdk-man.md
> +This structure is available since SDK API 1.9.
These 3 typedef's were added in 1.17

2021-01-27 22:31 UTC, dmitryermilov commented on doc/mediasdk-man.md
> +This structure is available since SDK API 1.9.
@daleksan ?

2021-03-29 13:51 UTC, daleksan commented on doc/mediasdk-man.md
> +This structure is available since SDK API 1.9.
@dmitryermilov done, sorry for delay

2021-03-29 13:59 UTC, dmitryermilov approved these changes

2021-03-29 14:01 UTC, dmitryermilov requested changes

2021-03-29 14:01 UTC, dmitryermilov commented on doc/mediasdk-man.md
> +This structure is available since SDK API 1.9.
@daleksan, I still observe 1.9..

2021-03-29 16:40 UTC, daleksan commented on doc/mediasdk-man.md
> +This structure is available since SDK API 1.9.
now should be fixed :)

2021-03-29 21:02 UTC, dmitryermilov approved these changes

2021-03-29 21:02 UTC, merged