[hevce] Disable bit depth conversion
Intel-Media-SDK/MediaSDK pull request #2635
Opened 2021-03-24 13:49 UTC by yskuridi

Driver doesn't support 10b->8b and 8b->10b conversions.

Issue: MDP-65185
Test: manually

2021-03-24 20:42 UTC, dmitryermilov commented
@thomasli21801 , @vilichev , please review

2021-03-24 20:43 UTC, dmitryermilov submitted a review, later dismissed

2021-03-25 02:07 UTC, thomasli21801 requested changes
Hi Yuliya and Dmitry,
Bit depth conversion can be supported by HEVC VDEnc.
Can you help to make the change for VME specific?

Thanks,
Thomas

2021-03-25 12:04 UTC, dmitryermilov commented
@thomasli21801 , you said HW can support this. but you also mentioned it's not covered in validation. So do suggest to allow VDEnc case here (even it's not validated)? Just want to be on the same page.

2021-03-25 14:10 UTC, dmitryermilov commented
> > @thomasli21801 , you said HW can support this. but you also mentioned it's not covered in validation. So do suggest to allow VDEnc case here (even it's not validated)? Just want to be on the same page.
> 
> Hi Dmitry,
> Yes. HW can support this and it's not covered in validation since we thought there was no usage. But I would suggest to keep VDEnc to provide the ability to community and support bug fixing if any. (might be low risk as well).

Thanks, Thomas. It's fine to me.

2021-03-25 15:59 UTC, dmitryermilov commented
@yskuridi , LGTM but can you please update the comment that this change for VME only.

2021-03-26 01:02 UTC, JeremyShang approved these changes

2021-03-26 06:46 UTC, vilichev approved these changes

2021-03-26 06:57 UTC, thomasli21801 approved these changes

2021-03-26 09:12 UTC, merged