[sample_encode] parameter for TCBRC test was added
Intel-Media-SDK/MediaSDK pull request #2637
Opened 2021-03-25 18:27 UTC by ogolikov

Issue: -
Test: -

2021-03-30 10:34 UTC, takulako submitted a review, later dismissed

2021-03-31 08:49 UTC, AntonGrishin approved these changes

2021-03-31 09:48 UTC, onabiull requested changes
Please update sample_encode documentation with new parameter description.

2021-03-31 11:00 UTC, onabiull approved these changes

2021-03-31 11:01 UTC, merged

2021-03-31 11:03 UTC, dmitryermilov commented
@onabiull , for such  not trivial features it would be better to merge code **together with tests**