[Decode] Check whether the vui_ext_num_entries exceeds the specified value
Intel-Media-SDK/MediaSDK pull request #2884
Opened 2022-02-14 06:56 UTC by chuanli1

Issue: MDP-68766
Test: manual

2022-02-14 07:00 UTC, wangyan-intel requested changes

2022-02-14 07:00 UTC, wangyan-intel commented on _studio/shared/umc/codec/h264_dec/src/umc_h264_dec_bitstream_headers.cpp
> +    if(vui.vui_ext_num_entries > 1024)
Could we use macro instead of 1024?

2022-02-17 09:41 UTC, wangyan-intel approved these changes

2022-02-23 08:49 UTC, chuanli1 commented
Hi Dmitry, could you merge this PR? Thanks.

2022-02-24 06:46 UTC, dmitryermilov approved these changes
LGTM

2022-02-24 06:46 UTC, merged

2022-02-24 06:58 UTC, dmitryermilov commented
> @dmitryermilov, Hi Dmitry, could you review this PR? Thanks.

Done!