Update codeowners
Intel-Media-SDK/MediaSDK pull request #2933
Opened 2022-05-26 06:54 UTC by Sherry-Lin

2022-05-27 02:31 UTC, guowillyy commented
mpeg2d owner should be Will and Yan.

2022-05-27 06:13 UTC, Sherry-Lin commented
> mpeg2d owner should be Will and Yan.

Thanks for correction. Updated patch.

2022-06-01 15:16 UTC, dvrogozh requested changes

2022-06-01 15:16 UTC, dvrogozh commented on CODEOWNERS
> +/_studio/enctools/ @Intel-Media-SDK/mediasdk-admin dmitry.v.rogozhkin@intel.com
We need appropriate owner for enctools part. I am not the one. sergey.plotnikov@intel.com might be the candidate.

2022-06-02 05:20 UTC, Sherry-Lin commented
@dvrogozh thanks. Updated patch.

2022-06-07 01:56 UTC, dvrogozh approved these changes
Looks good.

2022-06-07 02:21 UTC, merged